# Generated by Django 5.0.9 on 2024-12-13 16:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceindividualpage_serviceseparatepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='service_index_pages', to='services.servicepage'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='services.servicecategory'),
        ),
    ]
