# Generated by Django 5.0.9 on 2024-12-13 16:40

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_serviceindexpage_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecollectionspage',
            name='services',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='category',
        ),
        migrations.AddField(
            model_name='servicecollectionspage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='service_index_pages', to='services.servicepage'),
        ),
    ]
