# Generated by Django 5.0.9 on 2024-12-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicecollectionspage_botton_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecollectionspage',
            old_name='botton_text',
            new_name='bottom_text',
        ),
        migrations.RenameField(
            model_name='serviceindexpage',
            old_name='botton_text',
            new_name='bottom_text',
        ),
        migrations.RenameField(
            model_name='serviceindividualpage',
            old_name='botton_text',
            new_name='bottom_text',
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='botton_text',
            new_name='bottom_text',
        ),
        migrations.RenameField(
            model_name='serviceseparatepage',
            old_name='botton_text',
            new_name='bottom_text',
        ),
    ]
