# Generated by Django 5.0.9 on 2024-12-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_botton_text_servicecollectionspage_bottom_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
