# Generated by Django 5.0.9 on 2024-12-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_servicecollectionspage_service_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecollectionspage',
            name='description1',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicecollectionspage',
            name='description2',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicecollectionspage',
            name='description3',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
