# Generated by Django 5.0.9 on 2024-12-25 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_servicepage_description1_servicepage_description2_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecollectionspage',
            name='bottom_text',
            field=models.TextField(blank=True, help_text='CHALLENGES ORGANIZED||International Events (Participation and Attended)||NATIONAL / INTERNATIONAL CONFERENCES||KEY NOTE ADDRESSES –NATIONAL / INTERNATIONAL CONFERENCES||TECHNICAL TALKS||SEMINAR, CONFERENCE, WORKSHOP ORGANISED||SEMINAR, WORKSHOP ATTENDED in TLP||SEMINAR, CONFERENCE, WORKSHOP ATTENDED in CORE AREA||SPONSORED Conferences/ STTP/ FDPs', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicecollectionspage',
            name='service_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='servicecollectionspage',
            name='service_image1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='servicecollectionspage',
            name='service_image2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='servicecollectionspage',
            name='service_image3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='bottom_text',
            field=models.TextField(blank=True, help_text='BOOKS,BOOKS CHAPTERS,RESEARCH PUBLICATIONS (PEER-REVIEWED JOURNALS)', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='service_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='service_image1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='service_image2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='service_image3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='serviceseparatepage',
            name='bottom_text',
            field=models.TextField(blank=True, help_text='FACULTY INTERSHIP||CONSULTANCY PROJECT||MOOC DEVELOPMENT||CERTIFICATE||ACHIEVEMENTS', max_length=255),
        ),
    ]
