# Generated by Django 5.0.9 on 2024-12-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='File_content',
            field=models.FileField(blank=True, help_text='Upload a file', null=True, upload_to='files/'),
        ),
    ]
