# Generated by Django 5.0.9 on 2024-12-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='File_content',
        ),
    ]
